//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tled.rc
//
#define IDS_BASIS_ADDRESS               1
#define IDS_EVAL_WARNING                2
#define IDD_SWITCH_ATTR                 101
#define IDD_SEG_ATTRIBUTES              102
#define IDC_EXECUTABLE_EXPIRES_AT       102
#define IDD_JOINT                       103
#define IDD_SCALE                       104
#define IDD_EDIT_SIGNAL                 106
#define IDD_EDIT_EXLIGHT                107
#define IDD_SHIFT                       108
#define IDD_EDIT_TEXT                   109
#define IDC_SWITCH_EDIT                 1000
#define IDC_SWITCH_IS_A                 1001
#define IDC_SWITCH_IS_B                 1002
#define IDC_RADIO3                      1003
#define IDC_ETEXT_HEIGHT_DEFAULT        1003
#define IDC_HELPx                       1004
#define IDC_ETEXT_HEIGHT_CUSTOM         1004
#define IDC_SWITCH_HEURISTICATE         1005
#define IDC_ETEXT_WIDTH_DEFAULT         1005
#define IDC_SWITCH_WARN                 1006
#define IDC_ETEXT_WIDTH_CUSTOM          1006
#define IDC_SWITCH_ROTATE               1007
#define IDC_SWITCH_SWAP_NORMAL          1007
#define IDC_ETEXT_WEIGHT_DEFAULT        1007
#define IDC_SWITCH_IS_SINGLETON         1008
#define IDC_ETEXT_WEIGHT_NORMAL         1008
#define IDC_ETEXT_WEIGHT_BOLD           1009
#define IDC_ETEXT_WEIGHT_CUSTOM         1010
#define IDC_CHECK1                      1011
#define IDC_EDIT_SEG_COUNTS_DISTANCE    1011
#define IDC_CHECK2                      1012
#define IDC_EDIT_SEG_LIGHTS             1012
#define IDC_CHECK3                      1013
#define IDC_EDIT_SEG_VISIBLE            1013
#define IDC_ITALIC                      1013
#define IDC_CHECK4                      1014
#define IDC_EDIT_SEG_SUBDIVIDE          1014
#define IDC_EDIT1                       1015
#define IDC_EDIT_SEG_TC                 1015
#define IDC_EDIT_XLIGHT_XLNO            1015
#define IDC_EDIT_SIG_TRACK_ID           1015
#define IDC_SHIFT_X                     1015
#define IDC_TEXT_TEXT                   1015
#define IDC_PANELLIGHT_RADIUS           1015
#define IDC_PANELSWITCH_STRING          1015
#define IDC_JOINT_INSULATED             1017
#define IDC_JOINT_WPX                   1018
#define IDC_EDIT2                       1019
#define IDC_PANELLIGHT_STRING           1019
#define IDC_PANELSWITCH_NOMENCLATURE    1019
#define IDC_EDIT3                       1020
#define IDC_JOINT_WPY                   1020
#define IDC_SHIFT_Y                     1020
#define IDC_ETEXT_HEIGHT_EDIT           1020
#define IDC_PANELLIGHT_RED              1020
#define IDC_EDIT4                       1021
#define IDC_ETEXT_WIDTH_EDIT            1021
#define IDC_PANELLIGHT_YELLOW           1021
#define IDC_EDIT5                       1022
#define IDC_JOINT_RWY                   1022
#define IDC_ETEXT_WEIGHT_EDIT           1022
#define IDC_PANELLIGHT_GREEN            1022
#define IDC_EDIT6                       1023
#define IDC_JOINT_ELEVATION             1023
#define IDC_PANELLIGHT_WHITE            1023
#define IDC_SWITCH_EDIT_JOINT_ATTRIBUTES 1024
#define IDC_SCALE_EDIT                  1025
#define IDC_BUTTON1                     1026
#define IDC_EDIT_SIGNAL_JOINT           1026
#define IDC_EDIT_SEG_SHOW_TC            1026
#define IDC_SWITCH_HILITE_NORMAL        1026
#define IDC_SCALE_P5                    1026
#define IDC_ETEXT_FACE_SELECT           1026
#define IDC_EDIT_SIG_LEVER              1027
#define IDC_SCALE_P7                    1027
#define IDC_EDIT_SIG_IJID               1028
#define IDC_SCALE_P8                    1028
#define IDC_EDIT_SIG_ORIENTATION        1029
#define IDC_SCALE_1                     1029
#define IDC_EDIT_SIG_STOP               1030
#define IDC_EDIT_SIG_ST                 1031
#define IDC_EDIT_SIG_GT                 1032
#define IDC_EDIT_SIG_STATION_NO         1034
#define IDC_EDIT_SIG_ST_NO              1035
#define IDC_JOINT_STATION_ID            1036
#define IDC_JOINT_RWX                   1037
#define IDC_EDIT_SIG_HEADS              1038
#define IDC_EDIT_XLIGHT_IJNO            1039
#define IDC_EDIT_XLIGHT_ORIENT          1040
#define IDC_EDIT_SEG_SPREAD             1041
#define IDC_SWKEY_WPX                   1042
#define IDC_SWKEY_WPY                   1043
#define IDC_SWKEY_LEVER                 1044
#define IDC_ETEXT_FACE_DEFAULT          1045
#define IDC_ETEXT_FACE_CUSTOM           1046
#define IDC_ETEXT_FACE_SELECTION        1047
#define IDC_ETEXT_COLOR_DEFAULT         1048
#define IDC_ETEXT_COLOR_CUSTOM          1049
#define IDC_ETEXT_COLOR_SELECT          1050
#define IDC_ETEXT_SAMPLE                1051
#define IDC_ETEXT_WIDTH_SPIN            1053
#define IDC_ETEXT_HEIGHT_SPIN           1054
#define IDC_ETEXT_WEIGHT_SPIN           1055
#define IDC_EXECUTABLE_EXPIRES          1056
#define IDC_TRAFFICLEVER_LEVER          1057
#define IDC_TRAFFICLEVER_WPX            1058
#define IDC_TRAFFICLEVER_WPY            1059
#define IDC_TRAFFICLEVER_LEFT           1061
#define IDC_TRAFFICLEVER_RIGHT          1062
#define IDC_PANELLIGHT_LEVER            1063
#define IDC_PANELLIGHT_WPX              1064
#define IDC_PANELLIGHT_WPY              1065
#define IDC_PANELSWITCH_LEVER           1067
#define IDC_PANELSWITCH_WPX             1068
#define IDC_PANELSWITCH_WPY             1069
#define IDD_SWKEY                       2007
#define IDD_TRAFFICLEVER                2008
#define IDD_PANELLIGHT                  2009
#define IDD_PANELSWITCH                 2010
#define IDC_ETEXT_WPX                   2011
#define IDC_ETEXT_WPY                   2012
#define IDC_MAC_SEND_COLOR              2013
#define IDC_MAC_GET_COLOR               2014 // up to date now
#define IDM_SCALE                       40001
#define IDM_SHIFT                       40002
#define IDM_FIX_ORIGIN                  40003
#define IDM_SHIFT_ORIGIN                40004
#define IDM_FIX_VIEW                    40005
#define IDC_STATIC                      -1
#define IDC_RELEASE_NOTE                65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
