#ifndef _NX_LISP_FASDUMP_H__
#define _NX_LISP_FASDUMP_H__

const int
   FASD_1BNUM =       1,
   FASD_2BNUM    =    2,
   FASD_ATSYM =       3,
   FASD_RLYSYM=       4,
   FASD_LIST =        5,
   FASD_VECTOR =      6,
   FASD_LONG   =      7,
   FASD_STRING =      8,
   FASD_CHAR   =      9,
   FASD_4BNUM  =     10,
   FASD_8BNUM  =     11,
   FASD_VERSION  =    254,
   FASD_EOF      =    255;




#endif
